import {
  Utensils,
  ShoppingCart,
  Wine,
  Car,
  Building,
  Plane,
  Bus,
  Fuel,
  MapPin,
  Home,
  Zap,
  Smartphone,
  Shield,
  Gift,
  Activity,
  Receipt,
  Bike,
  Monitor,
  Gamepad2,
  Film,
  Music,
  Trophy,
  Package,
  PawPrint,
  Wrench,
  Sparkles,
  Flame,
  Trash2,
  Tv,
  Droplets,
  Baby,
  Shirt,
  BookOpen,
  CircleDot,
  type LucideIcon,
} from 'lucide-react-native';

export interface CategoryMeta {
  icon: LucideIcon;
  color: string;
}

export const CATEGORY_META: Record<string, CategoryMeta> = {
  'Dining Out':          { icon: Utensils,    color: '#F59E0B' },
  'Groceries':           { icon: ShoppingCart, color: '#10B981' },
  'Liquor':              { icon: Wine,         color: '#8B5CF6' },
  'Taxi':                { icon: Car,          color: '#EF4444' },
  'Hotel':               { icon: Building,     color: '#3B82F6' },
  'Plane':               { icon: Plane,        color: '#0EA5E9' },
  'Bus/Train':           { icon: Bus,          color: '#6366F1' },
  'Gas/Fuel':            { icon: Fuel,         color: '#F97316' },
  'Parking':             { icon: MapPin,       color: '#64748B' },
  'Rent':                { icon: Home,         color: '#0891B2' },
  'Electricity':         { icon: Zap,          color: '#EAB308' },
  'Phone/Internet':      { icon: Smartphone,   color: '#06B6D4' },
  'Insurance':           { icon: Shield,       color: '#64748B' },
  'Gift':                { icon: Gift,         color: '#EC4899' },
  'Medical Expenses':    { icon: Activity,     color: '#EF4444' },
  'Taxes':               { icon: Receipt,      color: '#6B7280' },
  'Bicycle':             { icon: Bike,         color: '#10B981' },
  'Car':                 { icon: Car,          color: '#3B82F6' },
  'Other Electronics':   { icon: Monitor,      color: '#8B5CF6' },
  'Games':               { icon: Gamepad2,     color: '#7C3AED' },
  'Movies':              { icon: Film,         color: '#6D28D9' },
  'Movies / Games':      { icon: Film,         color: '#7C3AED' },
  'Music':               { icon: Music,        color: '#EC4899' },
  'Sports':              { icon: Trophy,       color: '#F59E0B' },
  'Furniture':           { icon: Package,      color: '#92400E' },
  'Household Supplies':  { icon: Package,      color: '#0891B2' },
  'Mortgage':            { icon: Home,         color: '#1D4ED8' },
  'Pets':                { icon: PawPrint,     color: '#F97316' },
  'Services':            { icon: Wrench,       color: '#64748B' },
  'Cleaning':            { icon: Sparkles,     color: '#06B6D4' },
  'Heat':                { icon: Flame,        color: '#EF4444' },
  'Trash':               { icon: Trash2,       color: '#6B7280' },
  'TV':                  { icon: Tv,           color: '#3B82F6' },
  'Water':               { icon: Droplets,     color: '#0EA5E9' },
  'Child Care':          { icon: Baby,         color: '#EC4899' },
  'Clothing':            { icon: Shirt,        color: '#8B5CF6' },
  'Education':           { icon: BookOpen,     color: '#1D4ED8' },
  'Other':               { icon: CircleDot,    color: '#6B7280' },
};

export const DEFAULT_CATEGORY_META: CategoryMeta = {
  icon: CircleDot,
  color: '#6B7280',
};
